import type { Metadata } from "next"
import { NextIntlClientProvider } from "next-intl"
import { getLocale, getMessages } from "next-intl/server"
import { Geist } from "next/font/google"
import ThemeProvider from "../components/ThemeProvider"
import "../styles/globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: [ "latin" ]
})

export const metadata: Metadata = {
  title: "Open-Source Portfolio",
  description: "Generated by create next app"
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased bg-white dark:bg-black`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}